name: keep_app
description: "Clone keep from scratch with Flutter"

version: 1.0.0+1
environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  audioplayers: ^6.0.0
  bloc: ^8.1.4
  camera: ^0.10.5+9
  cloud_firestore: ^4.16.1
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  firebase_storage: ^11.7.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_lorem: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  gap: ^3.0.1
  go_router: ^13.2.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  image_picker: ^1.0.8
  internet_connection_checker_plus: ^2.3.0
  intl: ^0.18.1
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  pointycastle: ^3.8.0
  provider: ^6.1.2
  record: ^4.4.4
  rxdart: ^0.27.7
  flutter_native_splash: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.9
  # gen image svg fonts
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  # gen hive model
  hive_generator: ^2.0.1
  # gen locale
  intl_utils: ^2.8.7
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/png/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/jpg/
  generate: true

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: assets/lang # Optional. Directory ARB files. Default: lib/l10n
  output_dir: lib/gen # Optional. Directory Generated localization files. Default: lib/generated

flutter_gen:
  output: lib/gen/ # Optional, default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  colors:
    inputs:
      - assets/colors/colors.xml

flutter_native_splash:
  color: "#ffffff"
  background_image: "assets/png/splash_light.png"
  color_dark: "#121212"
  background_image_dark: "assets/png/splash_dark.png"

  android: true
  ios: false
  web: false
